CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."activity_log" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_activity_log"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 


CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."admins" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_admins"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."admins" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/admins/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_admins")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_addresses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_addresses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_addresses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_addresses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_addresses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_insurance_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurance_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_insurance_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_insurance_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurance_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."attribute_entities" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_entities"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."attribute_entities" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/attribute_entities/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_entities")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."attribute_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."attribute_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/attribute_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."bank_details" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_bank_details"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."bank_details" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/bank_details/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_bank_details")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."bridge_drawdown_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_bridge_drawdown_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."bridge_drawdown_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/bridge_drawdown_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_bridge_drawdown_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."charge_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_charge_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."charge_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/charge_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_charge_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_form_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_form_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_form_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_form_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_form_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."companies" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_companies"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."companies" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/companies/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_companies")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."currencies" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_currencies"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."currencies" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/currencies/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_currencies")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_aborted_reasons" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_aborted_reasons"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_aborted_reasons" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_aborted_reasons/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_aborted_reasons")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_document_risk" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_risk"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_document_risk" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_document_risk/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_risk")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_statuses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_statuses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_statuses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_statuses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_statuses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."document_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_document_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."document_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/document_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_document_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_amount_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_amount_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_amount_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_event_amount_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_amount_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_event_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."failed_jobs" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_failed_jobs"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."failed_jobs" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/failed_jobs/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_failed_jobs")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."fee_options" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_options"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."fee_options" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/fee_options/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_options")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."fee_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."fee_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/fee_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."fee_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."fee_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/fee_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."form_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_form_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."form_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/form_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_form_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."guarantor_corporates" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_corporates"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."guarantor_corporates" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/guarantor_corporates/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_corporates")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."guarantor_individuals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_individuals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."guarantor_individuals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/guarantor_individuals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_individuals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."guarantor_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."guarantor_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/guarantor_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantor_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."interest_calculation_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_calculation_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."interest_calculation_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/interest_calculation_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_calculation_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."interest_subtypes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_subtypes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."interest_subtypes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/interest_subtypes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_subtypes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."interest_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."interest_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/interest_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_interest_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."introducer_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_introducer_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."introducer_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/introducer_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_introducer_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."jobs" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_jobs"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."jobs" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/jobs/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_jobs")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."lending_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lending_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."lending_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/lending_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lending_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."loan_calculation_method" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_calculation_method"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."loan_calculation_method" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/loan_calculation_method/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_calculation_method")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."marital_statuses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_marital_statuses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."marital_statuses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/marital_statuses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_marital_statuses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."marketing_sources" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_marketing_sources"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."marketing_sources" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/marketing_sources/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_marketing_sources")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."migrations" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_migrations"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."migrations" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/migrations/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_migrations")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."name_titles" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_name_titles"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."name_titles" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/name_titles/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_name_titles")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."order_statuses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_order_statuses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."order_statuses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/order_statuses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_order_statuses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."ownership_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_ownership_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."ownership_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/ownership_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_ownership_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."password_resets" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_password_resets"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."password_resets" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/password_resets/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_password_resets")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."payment_providers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payment_providers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."payment_providers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/payment_providers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payment_providers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."payments" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payments"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."payments" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/payments/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payments")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."permission_category" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_category"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."permission_category" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/permission_category/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_category")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."permission_groups" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_groups"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."permission_groups" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/permission_groups/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_groups")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."personal_access_tokens" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_personal_access_tokens"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."personal_access_tokens" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/personal_access_tokens/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_personal_access_tokens")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."profile_approval_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_profile_approval_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."profile_approval_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/profile_approval_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_profile_approval_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."provider_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_provider_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."provider_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/provider_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_provider_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."purpose_credit_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_purpose_credit_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."purpose_credit_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/purpose_credit_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_purpose_credit_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."quotes_status" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes_status"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."quotes_status" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/quotes_status/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes_status")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."roles" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_roles"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."roles" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/roles/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_roles")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."sharepoint_updates_timestamps" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_sharepoint_updates_timestamps"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."sharepoint_updates_timestamps" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/sharepoint_updates_timestamps/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_sharepoint_updates_timestamps")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."stripe_settings" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_stripe_settings"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."stripe_settings" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/stripe_settings/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_stripe_settings")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."systems_deal_setting_groups" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_systems_deal_setting_groups"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."systems_deal_setting_groups" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/systems_deal_setting_groups/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_systems_deal_setting_groups")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."use_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_use_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."use_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/use_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_use_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."user_types" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_user_types"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."user_types" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/user_types/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_user_types")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."valuation_statuses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_valuation_statuses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."valuation_statuses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/valuation_statuses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_valuation_statuses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."variable_rate_settings" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rate_settings"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."variable_rate_settings" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/variable_rate_settings/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rate_settings")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."variable_rate_sources" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rate_sources"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."variable_rate_sources" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/variable_rate_sources/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rate_sources")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."addresses" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_addresses"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."addresses" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/addresses/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_addresses")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."attribute_groups" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_groups"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."attribute_groups" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/attribute_groups/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_groups")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."attributes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attributes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."attributes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/attributes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attributes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."brokers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_brokers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."brokers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/brokers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_brokers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_companies" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_companies"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_companies" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_companies/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_companies")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_groups" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_groups"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_groups" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_groups/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_groups")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."documents" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_documents"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."documents" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/documents/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_documents")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_event_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_event_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_event_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."fee_type_lending_type" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_type_lending_type"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."fee_type_lending_type" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/fee_type_lending_type/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fee_type_lending_type")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."introducers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_introducers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."introducers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/introducers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_introducers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."lenders" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lenders"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."lenders" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/lenders/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lenders")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."model_has_roles" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_model_has_roles"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."model_has_roles" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/model_has_roles/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_model_has_roles")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."payment_attempts" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payment_attempts"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."payment_attempts" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/payment_attempts/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_payment_attempts")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."permissions" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permissions"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."permissions" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/permissions/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permissions")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."role_has_permissions" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_role_has_permissions"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."role_has_permissions" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/role_has_permissions/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_role_has_permissions")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."service_providers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_service_providers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."service_providers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/service_providers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_service_providers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."systems_deal_setting" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_systems_deal_setting"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."systems_deal_setting" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/systems_deal_setting/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_systems_deal_setting")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."task_group" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_task_group"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."task_group" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/task_group/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_task_group")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."variable_rates" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."variable_rates" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/variable_rates/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."variable_rates_history" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates_history"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."variable_rates_history" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/variable_rates_history/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates_history")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."variable_rates_history_copy1" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates_history_copy1"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."variable_rates_history_copy1" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/variable_rates_history_copy1/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_variable_rates_history_copy1")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."lender_funder_interest_rate" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lender_funder_interest_rate"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."lender_funder_interest_rate" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/lender_funder_interest_rate/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lender_funder_interest_rate")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."model_has_permissions" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_model_has_permissions"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."model_has_permissions" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/model_has_permissions/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_model_has_permissions")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."permission_group_permission" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_group_permission"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."permission_group_permission" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/permission_group_permission/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_permission_group_permission")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."task" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_task"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."task" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/task/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_task")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_client_companies" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_client_companies"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_client_companies" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_client_companies/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_client_companies")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_client_individuals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_client_individuals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_client_individuals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_client_individuals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_client_individuals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_insurance_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurance_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_insurance_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_insurance_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurance_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."asset_insurances" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurances"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."asset_insurances" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/asset_insurances/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_asset_insurances")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."assets" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_assets"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."assets" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/assets/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_assets")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."attribute_values" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_values"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."attribute_values" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/attribute_values/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_attribute_values")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."audit" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_audit"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 



CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."borrowers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_borrowers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."borrowers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/borrowers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_borrowers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."broker_agent_deals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agent_deals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."broker_agent_deals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/broker_agent_deals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agent_deals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."broker_agent_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agent_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."broker_agent_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/broker_agent_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agent_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."broker_agents" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agents"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."broker_agents" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/broker_agents/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_agents")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."broker_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."broker_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/broker_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_broker_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."ccr_reports" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_ccr_reports"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."ccr_reports" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/ccr_reports/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_ccr_reports")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."charges" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_charges"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."charges" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/charges/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_charges")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_company_clients" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_company_clients"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_company_clients" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_company_clients/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_company_clients")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_company_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_company_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_company_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_company_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_company_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_form_attachments" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_form_attachments"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_form_attachments" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_form_attachments/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_form_attachments")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_forms" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_forms"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_forms" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_forms/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_forms")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_group_clients" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_group_clients"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_group_clients" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_group_clients/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_group_clients")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_individual_credit_data" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individual_credit_data"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_individual_credit_data" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_individual_credit_data/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individual_credit_data")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_individual_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individual_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_individual_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_individual_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individual_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."client_individuals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individuals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."client_individuals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/client_individuals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_client_individuals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_activities" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_activities"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_activities" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_activities/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_activities")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_document_categories" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_categories"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_document_categories" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_document_categories/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_categories")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_document_categories_data" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_categories_data"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_document_categories_data" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_document_categories_data/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_document_categories_data")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_documents" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_documents"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_documents" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_documents/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_documents")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_introducers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_introducers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_introducers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_introducers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_introducers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_notification_rules" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notification_rules"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_notification_rules" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_notification_rules/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notification_rules")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_notification_rules_recipients" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notification_rules_recipients"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_notification_rules_recipients" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_notification_rules_recipients/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_notification_rules_recipients")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_rate_floors" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_rate_floors"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_rate_floors" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_rate_floors/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_rate_floors")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_setting_groups" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_setting_groups"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_setting_groups" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_setting_groups/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_setting_groups")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_settings" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_settings"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_settings" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_settings/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_settings")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_task" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_task"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_task" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_task/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_task")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deal_task_group" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_task_group"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deal_task_group" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deal_task_group/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deal_task_group")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."deals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."deals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/deals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_deals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."delegated_owners" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_delegated_owners"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."delegated_owners" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/delegated_owners/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_delegated_owners")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_events" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_events"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_events" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_events/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_events")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_fees" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_fees"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_fees" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_fees/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_fees")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdown_fields_approval" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_fields_approval"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdown_fields_approval" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdown_fields_approval/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdown_fields_approval")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."drawdowns" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdowns"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."drawdowns" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/drawdowns/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_drawdowns")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."email_code_authentication" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_email_code_authentication"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."email_code_authentication" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/email_code_authentication/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_email_code_authentication")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."exit_fee_tiers" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_exit_fee_tiers"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."exit_fee_tiers" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/exit_fee_tiers/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_exit_fee_tiers")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."fees" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fees"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."fees" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/fees/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_fees")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."files" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_files"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."files" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/files/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_files")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."guarantors" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantors"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."guarantors" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/guarantors/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_guarantors")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."lender_operational_team_admin" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lender_operational_team_admin"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."lender_operational_team_admin" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/lender_operational_team_admin/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_lender_operational_team_admin")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."linked_deals" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_linked_deals"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."linked_deals" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/linked_deals/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_linked_deals")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."loan_administrators" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_administrators"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."loan_administrators" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/loan_administrators/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_administrators")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."loan_custom_forms" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_custom_forms"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."loan_custom_forms" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/loan_custom_forms/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_loan_custom_forms")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."margin_override" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_margin_override"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."margin_override" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/margin_override/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_margin_override")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."notes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."notes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/notes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."notification" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."notification" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/notification/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."notification_recipients" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_recipients"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."notification_recipients" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/notification_recipients/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_recipients")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."notification_rules" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_rules"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."notification_rules" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/notification_rules/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_rules")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."notification_templates" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_templates"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."notification_templates" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/notification_templates/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_notification_templates")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."orders" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_orders"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."orders" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/orders/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_orders")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."quote_note" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quote_note"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."quote_note" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/quote_note/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quote_note")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."quotes" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."quotes" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/quotes/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."quotes_recipients" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes_recipients"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."quotes_recipients" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/quotes_recipients/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_quotes_recipients")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."scheduled_notifications" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_scheduled_notifications"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."scheduled_notifications" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/scheduled_notifications/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_scheduled_notifications")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."users" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_users"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."users" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/users/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_users")
ON_ERROR=ABORT_STATEMENT;

CREATE OR REPLACE TABLE "DATA_WAREHOUSE"."STAGING_LD"."valuations" ( RAWDATA VARIANT ); 

CREATE OR REPLACE FILE FORMAT "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_valuations"
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "DATA_WAREHOUSE"."STAGING_LD"."valuations" 
FROM @DATA_WAREHOUSE.STAGING_LD.AZURE_DATA_LAKE_LD
PATTERN = '.*QA/valuations/.*'
FILE_FORMAT = (FORMAT_NAME = "DATA_WAREHOUSE"."STAGING_LD"."FF_LD_JSON_valuations")
ON_ERROR=ABORT_STATEMENT;
